---
title: "Week 3"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(rethinking)
library(MASS)
library(dagitty)
```

```{r}
data(WaffleDivorce)
d <- WaffleDivorce

# standardize variables

d$D <- standardize( d$Divorce )
d$M <- standardize( d$Marriage )
d$A <- standardize( d$MedianAgeMarriage )

sd( d$MedianAgeMarriage )
```

```{r model 1}
# model 1: divorce ~ median_married_age

m5.1 <- quap(
  alist(
    D ~ dnorm( mu , sigma ) ,
    mu <- a + bA * A ,
    a ~ dnorm( 0 , 0.2 ) ,
    bA ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
    ) , data = d )

precis(m5.1)
set.seed(10)

# prior simulation

prior <- extract.prior( m5.1 ) # extract sample of a and bA from priors
mu <- link( m5.1 , post=prior , data=list( A=c(-2,2) ) ) # used prior samples to get mu
plot( NULL , xlim=c(-2,2) , ylim=c(-2,2) )
for ( i in 1:50 ) lines( c(-2,2) , mu[i,] , col=col.alpha("black",0.4) )


# compute percentile interval of mean

A_seq <- seq( from=-3 , to=3.2 , length.out=30 )
mu <- link( m5.1 , data=list(A=A_seq) )
mu.mean <- apply( mu , 2, mean )
mu.PI <- apply( mu , 2 , PI )

# plot it all

plot( D ~ A , data=d , col=rangi2 )
lines( A_seq , mu.mean , lwd=2 )
shade( mu.PI , A_seq )
```

```{r}
# model 2: divorce ~ marriage_rate

m5.2 <- quap(
  alist(
    D ~ dnorm( mu , sigma ) ,
    mu <- a + bM * M ,
    a ~ dnorm( 0 , 0.2 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
    ) , data = d )

precis(m5.2)

# compute percentile interval of mean

M_seq <- seq( from=-3 , to=3.2 , length.out=30 )
mu <- link( m5.2 , data=list(M=M_seq) )
mu.mean <- apply( mu , 2, mean )
mu.PI <- apply( mu , 2 , PI )

# plot it all

plot( D ~ M , data=d , col=rangi2 )
lines( A_seq , mu.mean , lwd=2 )
shade( mu.PI , M_seq )
```

```{r}
DMA_dag1 <- dagitty("dag{ D <- A -> M -> D }")
coordinates(DMA_dag1) <- list( x=c(A=0,D=1,M=2) , y=c(A=0,D=1,M=0) )
drawdag( DMA_dag1 )
impliedConditionalIndependencies( DMA_dag1 )

DMA_dag2 <- dagitty( "dag{ D <- A -> M }" )
coordinates(DMA_dag2) <- list( x=c(A=0,D=1,M=2) , y=c(A=0,D=1,M=0) )
drawdag( DMA_dag2 )
impliedConditionalIndependencies( DMA_dag2 )
```

```{r}
m5.3 <- quap(
  alist(
    D ~ dnorm( mu , sigma ) ,
    mu <- a + bM*M + bA*A ,
    a ~ dnorm( 0 , 0.2 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    bA ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
    ) , data = d )

precis( m5.3 )
plot( coeftab(m5.1,m5.2,m5.3), par=c("bA","bM") )
```

```{r}
# marriage rate ~ median age ,not divorce ~ median age
m5.4 <- quap(
  alist(
    M ~ dnorm( mu , sigma ) ,
    mu <- a + bAM * A ,
    a ~ dnorm( 0 , 0.2 ) ,
    bAM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
    ) , data = d )

mu <- link(m5.4)
mu_mean <- apply( mu , 2 , mean )
mu_resid <- d$M - mu_mean

# visualize figure 5.4 first column: results from regressing marriage rate on age
result5.4 <- data.frame(marriage_res = mu_resid, std_marriage = d$M,
                        std_age = d$A, std_divorce = d$D)

age.seq <- seq( from=-2.5 , to=3 , by=0.2 )

mu <- link( m5.4 , data=data.frame(A=age.seq) )

# summarize the distribution of mu
mu.mean <- apply( mu , 2 , mean )
mu.PI <- apply( mu , 2 , PI , prob=0.89 )

# plot raw data
# fading out points to make line and interval more visible
plot( std_marriage ~ std_age , data=result5.4 , col=col.alpha("#0099CC",1) )

# plot the MAP line, aka the mean mu for each weight
lines( age.seq , mu.mean )

# plot a shaded region for 89% PI
shade( mu.PI , age.seq )


# divorce rate ~ residuals
resm5.4 <- quap(
  alist(
    std_divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bAM * marriage_res ,
    a ~ dnorm( 0 , 0.2 ) ,
    bAM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
    ) , data = result5.4 )

mres.seq <- seq( from=-1.75, to=1.9, by=0.05)

mu <- link(resm5.4, data=data.frame(marriage_res=mres.seq))
mu.mean <- apply( mu , 2 , mean )
mu.PI <- apply( mu , 2 , PI , prob=0.89 )

# a residual plot
plot( std_divorce ~ marriage_res , data=result5.4 , col=col.alpha("#0099CC",1) )

# plot the MAP line, aka the mean mu for each weight
lines( mres.seq , mu.mean )

# plot a shaded region for 89% PI
shade( mu.PI , mres.seq )
```

```{r}
# call link without specifying new data
# so it uses original data
mu <- link( m5.3 )

# summarize samples across cases
mu_mean <- apply( mu , 2 , mean )
mu_PI <- apply( mu , 2 , PI )

# simulate observations: unused
# again no new data, so uses original data
D_sim <- sim( m5.3 , n=1e4 )
D_PI <- apply( D_sim , 2 , PI )

plot( mu_mean ~ d$D , col=rangi2 , ylim=range(mu_PI) ,
      xlab="Observed divorce" , ylab="Predicted divorce" )

abline( a=0 , b=1 , lty=2 )
for ( i in 1:nrow(d) ) lines( rep(d$D[i],2) , mu_PI[,i] , col=rangi2 )
```

```{r}
m5.3_A <- quap(
  alist(
    ## A -> D <- M
    D ~ dnorm( mu , sigma ) ,
    mu <- a + bM*M + bA*A ,
    a ~ dnorm( 0 , 0.2 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    bA ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 ),
    ## A -> M
    M ~ dnorm( mu_M , sigma_M ),
    mu_M <- aM + bAM*A,
    aM ~ dnorm( 0 , 0.2 ),
    bAM ~ dnorm( 0 , 0.5 ),
    sigma_M ~ dexp( 1 )
    ) , data = d )

precis(m5.3_A)
A_seq <- seq( from=-2 , to=2 , length.out=30 )

# prep data
sim_dat <- data.frame( A=A_seq )

# simulate M and then D, using A_seq
s <- sim( m5.3_A , data=sim_dat , vars=c("M","D") )

plot( sim_dat$A , colMeans(s$D) , ylim=c(-2,2) , type="l" ,
      xlab="manipulated A" , ylab="counterfactual D" )

shade( apply(s$D,2,PI) , sim_dat$A )

mtext( "Total counterfactual effect of A on D" )

# new data frame, standardized to mean 26.1 and std dev 1.24
sim2_dat <- data.frame( A=(c(20,30)-26.1)/1.24 )
s2 <- sim( m5.3_A , data=sim2_dat , vars=c("M","D") )
mean( s2$D[,2] - s2$D[,1] )

sim_dat <- data.frame( M=seq(from=-2,to=2,length.out=30) , A=0 )
s <- sim( m5.3_A , data=sim_dat , vars="D" )

plot( sim_dat$M , colMeans(s) , ylim=c(-2,2) , type="l" ,
      xlab="manipulated M" , ylab="counterfactual D" )
shade( apply(s,2,PI) , sim_dat$M )
mtext( "Total counterfactual effect of M on D" )

# simulating counterfactuals without using `sim`
# post <- extract.samples( m5.3_A )
# M_sim <- with( post , sapply( 1:30 ,
#                               function(i) rnorm( 1e3 , aM + bAM*A_seq[i] , sigma_M ) ) )
# D_sim <- with( post , sapply( 1:30 ,
#                               function(i) rnorm( 1e3 , a + bA*A_seq[i] + bM*M_sim[,i] , sigma ) ) )
```

```{r}
# Masked associations:
# A popular hypothesis has it that primates with larger brains produce more energetic milk
data(milk)
d <- milk
str(d)

d$K <- standardize( d$kcal.per.g )
d$N <- standardize( d$neocortex.perc )
d$M <- standardize( log(d$mass) )

# d$neocortex.perc has null values

dcc <- d[ complete.cases(d$K,d$N,d$M) , ]

m5.5_draft <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bN*N ,
    a ~ dnorm( 0 , 1 ) ,
    bN ~ dnorm( 0 , 1 ) ,
    sigma ~ dexp( 1 )
  ) , data=dcc )

# prior visualization: not theoretically reasonable
prior <- extract.prior( m5.5_draft )
xseq <- c(-2,2)
mu <- link( m5.5_draft , post=prior , data=list(N=xseq) )

plot( NULL , xlim=xseq , ylim=xseq ,
      xlab="neocortex percent (std)" ,
      ylab="kilocal per g (std)")
for ( i in 1:50 ) lines( xseq , mu[i,] , col=col.alpha("black",0.5) )

m5.5 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bN*N ,
    a ~ dnorm( 0 , 0.2 ) ,
    bN ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data=dcc )

# prior visualization: the range of slopes is tighter and 0 std values intersect
prior <- extract.prior( m5.5 )
xseq <- c(-2,2)
mu <- link( m5.5 , post=prior , data=list(N=xseq) )

plot( NULL , xlim=xseq , ylim=xseq ,
      xlab="neocortex percent (std)" ,
      ylab="kilocal per g (std)")
for ( i in 1:50 ) lines( xseq , mu[i,] , col=col.alpha("black",0.5) )

precis( m5.5 )

xseq <- seq( from=min(dcc$N)-0.15 , to=max(dcc$N)+0.15 , length.out=30 )
mu <- link( m5.5 , data=list(N=xseq) )
mu_mean <- apply(mu,2,mean)
mu_PI <- apply(mu,2,PI)

plot( K ~ N , data=dcc ,
      xlab="neocortex percent (std)" ,
      ylab="kilocal per g (std)")
lines( xseq , mu_mean , lwd=2 )
shade( mu_PI , xseq )

# milk energy (kilocal) ~ log(body mass)
m5.6 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bM*M ,
    a ~ dnorm( 0 , 0.2 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data=dcc )

precis(m5.6)

xseq <- seq( from=min(dcc$M)-0.15 , to=max(dcc$M)+0.15 , length.out=30 )
mu <- link( m5.6 , data=list(M=xseq) )
mu_mean <- apply(mu,2,mean)
mu_PI <- apply(mu,2,PI)

plot( K ~ M , data=dcc ,
      xlab="log body mass (std)" ,
      ylab="kilocal per g (std)")
lines( xseq , mu_mean , lwd=2 )
shade( mu_PI , xseq )


# full milk energy model
m5.7 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bN*N + bM*M ,
    a ~ dnorm( 0 , 0.2 ) ,
    bN ~ dnorm( 0 , 0.5 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data=dcc )

# the coefficiants of both predictors now move away from 0
precis(m5.7)
plot( coeftab( m5.5 , m5.6 , m5.7 ) , pars=c("bM","bN") )

# a counterfactual plot: manipulating the value of body mass
xseq <- seq( from=min(dcc$M)-0.15 , to=max(dcc$M)+0.15 , length.out=30 )
mu <- link( m5.7 , data=data.frame( M=xseq , N=0 ) )
mu_mean <- apply(mu,2,mean)
mu_PI <- apply(mu,2,PI)

plot( NULL , xlim=range(dcc$M) , ylim=range(dcc$K) ,
      xlab="log body mass (std)" ,
      ylab="kilocal per g (std)")
mtext("Counterfactual holding N = 0")
lines( xseq , mu_mean , lwd=2 )
shade( mu_PI , xseq )

# Markov equivalents
dag5.7 <- dagitty( "dag{
M -> K <- N
M -> N }" )

coordinates(dag5.7) <- list( x=c(M=0,K=1,N=2) , y=c(M=0.5,K=1,N=0.5) )
MElist <- equivalentDAGs(dag5.7)
drawdag(MElist)
```

```{r}
# Categorical variables
data(Howell1)
d <- Howell1
str(d)

# indicator variables create unequal uncertainty
mu_female <- rnorm(1e4,178,20)
mu_male <- rnorm(1e4,178,20) + rnorm(1e4,0,10)
precis( data.frame( mu_female , mu_male ) )

# index variables treat categories equally, easier to assign priors, and easily scalable
d$sex <- ifelse( d$male==1 , 2 , 1 )
str( d$sex )

m5.8 <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a[sex] ,
    a[sex] ~ dnorm( 178 , 20 ) ,
    sigma ~ dunif( 0 , 50 )
  ) , data=d )

precis( m5.8 , depth=2 )

# calculate exptected difference in height between 2 categories
post <- extract.samples(m5.8)
post$diff_fm <- post$a[,1] - post$a[,2]
precis( post , depth=2 )

# Many categories
data(milk)
d <- milk
levels(d$clade)

d$clade_id <- as.integer( d$clade )

d$K <- standardize( d$kcal.per.g )

m5.9 <- quap(
  alist(
    K ~ dnorm( mu , sigma ),
    mu <- a[clade_id],
    a[clade_id] ~ dnorm( 0 , 0.5 ),
    sigma ~ dexp( 1 )
  ) , data=d )

labels <- paste( "a[" , 1:4 , "]:" , levels(d$clade) , sep="" )
plot( precis( m5.9 , depth=2 , pars="a" ) , labels=labels ,
      xlab="expected kcal (std)" )

# add a random categorical variable: [1] Gryffindor, [2] Hufflepuff, [3] Ravenclaw, and [4] Slytherin
set.seed(63)
d$house <- sample( rep(1:4,each=8) , size=nrow(d) )

m5.10 <- quap(
  alist(
    K ~ dnorm( mu , sigma ),
    mu <- a[clade_id] + h[house],
    a[clade_id] ~ dnorm( 0 , 0.5 ),
    h[house] ~ dnorm( 0 , 0.5 ),
    sigma ~ dexp( 1 )
  ) , data=d )

precis(m5.10, depth = 2)
```

