---
title: "Week 2"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(rethinking)
library(MASS)
library(splines)
```

```{r}
p_grid <- seq(0, 1, length.out=1000)
prob_p <- rep(1, 1000)
prob_data <- dbinom(round(0.7*15), size = 15, prob = p_grid)
posterior <- prob_data * prob_p
posterior <- posterior / sum(posterior)

post_samples <- sample(p_grid, prob = posterior, size = 1e4, replace = TRUE)

ggplot(data = data.frame(p_sample = post_samples), aes(p_sample)) +
  geom_density() + geom_vline(xintercept = 0.7, color = "red")

# HPDI(post_samples, prob = 0.95)

# uncertainty in parameter estimate is propagated through proportion of `post_samples`
W <- rbinom(1e4, size = 15, prob = post_samples)
ggplot(data = data.frame(w = W), aes(w)) + geom_histogram(bins = 16)

# only uncertainty in sampling remains
W <- rbinom(1e4, size = 15, prob = 0.7)
ggplot(data = data.frame(w = W), aes(w)) + geom_histogram(bins = 16)
```


```{r}
data(Howell1)
d <- Howell1

str(d)
precis(d)

adults <- d %>%
  filter(age >= 18)
```

```{r}
# baseline model w/ high prior variace for mu
flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm( 178 , 20 ),
  sigma ~ dunif( 0 , 50 )
)

m4.1 <- quap(flist, data = adults)
precis(m4.1)

# model w/ lower prior variance for mu
m4.2 <- quap(
  alist(
    height ~ dnorm( mu , sigma ),
    mu ~ dnorm( 178 , 0.1 ),
    sigma ~ dunif( 0 , 50 )
  ) , data=adults )

precis( m4.2 )
```

```{r}
vcov( m4.1 )
#cov2cor( vcov( m4.1 ) )

post_samples <- extract.samples( m4.1 , n=1e4 )
# post_samples <- mvrnorm(n=1e4 , mu=coef(m4.1) , Sigma=vcov(m4.1))

precis(post_samples)

ggplot(data = post_samples, aes(x = mu, y = sigma)) +
  geom_point()
```

# Prior predictive simulation

```{r}
plot( adults$height ~ adults$weight )

# prior simulation
set.seed(2971)

N <- 100 # 100 lines
a <- rnorm( N , 178 , 20 )
b <- rnorm( N , 0 , 10 )

plot( NULL , xlim=range(adults$weight) , ylim=c(-100,400), xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
mtext( "b ~ dnorm(0,10)" )
xbar <- mean(adults$weight)

for ( i in 1:N )
  curve( a[i] + b[i]*(x - xbar),
         from=min(adults$weight), to=max(adults$weight), add=TRUE,
         col=col.alpha("black",0.2) )

# positive slope only (b ~ log-normal distribution)
b <- rlnorm( 1e4 , 0 ,1)
dens( b , xlim=c(0,10) , adj=0.1 )

a <- rnorm( N , 178 , 20 )
b <- rlnorm( N , 0 , 1 )

plot( NULL , xlim=range(adults$weight) , ylim=c(-100,400), xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
mtext( "b ~ dnorm(0,10)" )
xbar <- mean(adults$weight)

for ( i in 1:N )
  curve( a[i] + b[i]*(x - xbar),
         from=min(adults$weight), to=max(adults$weight), add=TRUE,
         col=col.alpha("black",0.2) )
```

# Posterior distribution of estimates

```{r}
# define the average weight, x-bar
xbar <- mean(adults$weight)

# model fitting
m4.3 <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a + b*( weight - xbar ) ,
    a ~ dnorm( 178 , 20 ) ,
    b ~ dlnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 50 )
    ) , data=adults )

precis(m4.3)
round(vcov(m4.3), 3)
pairs(m4.3)

# mean posterior plot
post_samples <- extract.samples( m4.3 )
a_map <- mean(post_samples$a)
b_map <- mean(post_samples$b)
ggplot(data = adults, aes(x = weight, y = height)) +
  geom_point(col = "blue") +
  stat_function(fun = function(x) a_map + b_map*(x - xbar))

# varying sample size and uncertainty
N.vector <- c(10, 50, 150, 352)
for (N in N.vector) {
  dN <- adults[ 1:N , ]
  mN <- quap(
    alist(
      height ~ dnorm( mu , sigma ) ,
      mu <- a + b*( weight - mean(weight) ) ,
      a ~ dnorm( 178 , 20 ) ,
      b ~ dlnorm( 0 , 1 ) ,
      sigma ~ dunif( 0 , 50 )
      ) , data=dN )
  
  # extract 20 samples from the posterior
  post <- extract.samples( mN , n=20 )
  
  # display raw data and sample size
  plot( dN$weight , dN$height , xlim=range(adults$weight) , ylim=range(adults$height) ,
        col=rangi2 , xlab="weight" , ylab="height" )
  mtext(concat("N = ",N))
  
  # plot the lines, with transparency
  for ( i in 1:20 ) {
    curve( post$a[i] + post$b[i]*(x-mean(dN$weight)) ,
           col=col.alpha("black",0.3) , add=TRUE )
  }
}
```

# Posterior predictions

```{r}
# average mu posterior predictions

post <- extract.samples( m4.3 )
mu_at_50 <- post$a + post$b * ( 50 - xbar )
dens( mu_at_50 , col=rangi2 , lwd=2 , xlab="mu|weight=50" )

# define sequence of weights to compute predictions for
# these values will be on the horizontal axis
weight.seq <- seq( from=25 , to=70 , by=1 )

# use link to compute mu
# for each sample from posterior
# and for each weight in weight.seq
mu <- link( m4.3 , data=data.frame(weight=weight.seq) )
str(mu)

# use type=“n” to hide raw data
plot( height ~ weight , adults , type="n" )

# loop over samples and plot each mu value
for ( i in 1:100 )
  points( weight.seq , mu[i,] , pch=16 , col=col.alpha(rangi2,0.1) )

# summarize the distribution of mu
mu.mean <- apply( mu , 2 , mean )
mu.PI <- apply( mu , 2 , PI , prob=0.89 )
mu.HPDI <- apply( mu, 2, HPDI, prob=0.89 )

# plot raw data
# fading out points to make line and interval more visible
plot( height ~ weight , data=adults , col=col.alpha(rangi2,0.5) )

# plot the MAP line, aka the mean mu for each weight
lines( weight.seq , mu.mean )

# plot a shaded region for 89% PI
shade( mu.PI , weight.seq )


# posterior predictions of height

sim.height <- sim( m4.3 , data=list(weight=weight.seq), n=1e4)
str(sim.height)

height.PI <- apply( sim.height , 2 , PI , prob=0.89 )

# plot raw data
plot( height ~ weight , adults , col=col.alpha(rangi2,0.5) )

# draw MAP line
lines( weight.seq , mu.mean )

# draw HPDI region for line
shade( mu.HPDI , weight.seq )

# draw PI region for simulated heights
shade( height.PI , weight.seq )
```

# B-splines

```{r b-splines}
data(cherry_blossoms)
d <- cherry_blossoms
precis(d)

d2 <- d[ complete.cases(d$doy) , ] # complete cases on doy
num_knots <- 15
knot_list <- quantile( d2$year , probs=seq(0,1,length.out=num_knots) )

B <- bs(d2$year,
        knots=knot_list[-c(1,num_knots)] ,
        degree=3 , intercept=TRUE )

plot( NULL , xlim=range(d2$year) , ylim=c(0,1) , xlab="year" , ylab="basis" )
for ( i in 1:ncol(B) ) lines( d2$year , B[,i] )

m4.7 <- quap(
  alist(
    D ~ dnorm( mu , sigma ) ,
    mu <- a + B %*% w ,
    a ~ dnorm(100,10),
    w ~ dnorm(0,10),
    sigma ~ dexp(1)
    ), data=list( D=d2$doy , B=B ) ,
  start=list( w=rep( 0 , ncol(B) ) ) )

post <- extract.samples( m4.7 )
w <- apply( post$w , 2 , mean )
plot( NULL , xlim=range(d2$year) , ylim=c(-6,6) ,
      xlab="year" , ylab="basis * weight" )
for ( i in 1:ncol(B) ) lines( d2$year , w[i]*B[,i] )

mu <- link( m4.7 )
mu_PI <- apply(mu,2,PI,0.97)
plot( d2$year , d2$doy , col=col.alpha(rangi2,0.3) , pch=16 )
shade( mu_PI , d2$year , col=col.alpha("black",0.5) )
```

# Practices and Assignments

```{r}
# predict target weights

target.weight <- c(46.95, 43.72, 64.78, 32.59, 54.63)

# post <- extract.samples(m4.3)
# mu.link <- function(weight) post$a + post$b*( weight - xbar )
# mu <- sapply( target.weight , mu.link )

mu <- link( m4.3 , data=data.frame(weight=target.weight) )
mu.mean <- apply( mu, 2, mean )
mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 )

# post <- extract.samples(m4.3)
# sim.height <- sapply( target.weight , function(weight)
#   rnorm(
#     n=nrow(post) ,
#     mean=post$a + post$b*( weight - xbar ) ,
#     sd=post$sigma ) )

pred.height <- sim( m4.3 , data=list(weight=target.weight), n=1e4)
height.PI <- apply( pred.height , 2 , PI , prob=0.89 )

mu.mean
height.PI


# height ~ log(weight) model

data(Howell1)
d <- Howell1

plot( d$height ~ log(d$weight) )

# define the average log-weight
log.xbar <- mean(log(d$weight))

N <- 100
a <- rnorm( N , 178 , 20 )
b1 <- rlnorm( N , 0 , 1.75 )

plot( NULL , xlim=range(d$weight) , ylim=c(-100,400), xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
mtext( "b ~ dnorm(0,10)" )

for ( i in 1:N )
  curve( a[i] + b1[i]*(log(x) - log.xbar),
         from=min(d$weight), to=max(d$weight), add=TRUE,
         col=col.alpha("black",0.2) )

# model fitting
m4.8 <- quap(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a + b*( log(weight) - log.xbar ) ,
    a ~ dnorm( 178 , 20 ) ,
    b ~ dlnorm( 0 , 1.75 ) ,
    sigma ~ dunif( 0 , 50 )
    ) , data=d )

weight.seq <- seq( from=0 , to=70 , by=1 )

mu <- link( m4.8 , data=data.frame(weight=weight.seq) )
mu.mean <- apply( mu, 2, mean )
mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 )

pred.height <- sim( m4.8 , data=list(weight=weight.seq), n=1e4)
height.PI <- apply( pred.height , 2 , PI , prob=0.89 )

plot( height ~ weight , d , col=col.alpha(rangi2,0.5) )
lines( weight.seq , mu.mean )
shade( mu.HPDI , weight.seq )
shade( height.PI , weight.seq )


# polynomial prior predictive simulation

N <- 100
a <- rnorm( N , 178 , 20 )
b1 <- rlnorm( N , 0 , 0.25 )
b2 <- rnorm( N , 0 , 0.025 )

plot( NULL , xlim=range(d$weight) , ylim=c(-100,400), xlab="weight" , ylab="height" )
abline( h=0 , lty=2 )
abline( h=272 , lty=1 , lwd=0.5 )
mtext( "b ~ dnorm(0,10)" )
xbar <- mean(d$weight)

for ( i in 1:N )
  curve( a[i] + b1[i]*(x - xbar) + b2[i]*(x - xbar)^2,
         from=min(d$weight), to=max(d$weight), add=TRUE,
         col=col.alpha("black",0.2) )
```

